function [fitresult, gof] = createFit_Irene1(x, y, z)
%CREATEFIT(X,Y,Z)
%  Create a fit.
%
%  Data for 'Irene1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Nov-2016 17:23:52


% Fit: 'Irene1'.
[xData, yData, zData] = prepareSurfaceData( x, y, z );

% Set up fittype and options.
%  ft = fittype( 'loess' );
%  ft = fittype( 'poly22' );
  ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'off' );


% Plot fit with data.
%figure( 'Name', 'Irene1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Irene1', 'z vs. x, y', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
zlabel z
grid on
view( -64.7, 30.0 );


