function []=gridOutput(arg1)
% global function - main program

% Import x, y, z
fileID = fopen(char(arg1));
C = textscan(fileID,'%f %f %f');
x = C{1};
y = C{2};
z = C{3};

% Call function generated by the fit tool
[fitresult, gof] = createFit_Irene1(x, y, z);
coeffvals = coeffvalues(fitresult)
% Choose grid to be exported
xq = 0.0:0.1:15.0;
yq = 0:300:6000;

% create a larger grid (larger only in w, so in z)
xq1 = -15.0:0.1:30.0;
yq1 = yq;

% Create two arrays with all the coordinates pairs 
XQ = kron(xq, ones(1, length(yq)));
YQ = kron(ones(1, length(xq)), yq);

% Create two arrays with all the coordinates pairs 
XQ1 = kron(xq1, ones(1, length(yq1)));
YQ1 = kron(ones(1, length(xq1)), yq1);

% Interpolate
A = fitresult(XQ, YQ);
B = fitresult(XQ1, YQ1);
%  fitresult(8,3000)

% Plot
A = reshape(A, length(yq), length(xq));
%figure;
mesh(xq, yq, A);
A = reshape(A, 1, size(A,1)*size(A,2));

% Plot 2
B = reshape(B, length(yq1), length(xq1));
%figure;
mesh(xq1, yq1, B);
B = reshape(B, 1, size(B,1)*size(B,2));


% Export
%  OUT = [XQ; YQ; A]';
%  str = 'out';
%  dlmwrite(strcat(char(str),char(arg1)),OUT)

% Export 2
%  OUT = [XQ; YQ; A]';
str = 'par_';
dlmwrite(strcat(char(str),char(arg1)),coeffvals)
end





